### ISSUE TITLE
Can not use long integer object ID as a text

### ISSUE THREAD

**Issue by DrewNov** [typicode/json-server#273]
Hi, I am trying to use objects like this:
{
  "myObjects": [
    {"id": "1234567891234567891"},
    {"id": "1234567891234567892"},
    {"id": "1234567891234567893"}
  ]
}
http://localhost:3000/myObjects/1234567891234567891

It returns an empty object.
I am really need this working. Thanks.

**Comment by KillaBee1985** [comment]
@DrewNov It happens because in your db file you keep ID's value as strings but when this id parses by json-server it turns into number. 

For storing user data json-server uses [lowdb](https://github.com/typicode/lowdb) which uses [underscore-db](https://github.com/typicode/underscore-db) which has function getById. Soo... this function uses '===' operator to match ID's and in your case it turns into
`1234567891234567891 === "1234567891234567891"` and function returns empty object.

I am not sure is it bug or feature, but for workaround just use number values (without quotes) as your ID values.

**Comment by DrewNov** [comment]
Thanks.

But it's not workaround, because we are using string format of ids everywhere.
I have already tried to change it to not strings, but then somewhere in js, objects with this number ids, using for next queries, and ids become wrong value, because the number size is bigger then js integer type can contains.

So for example, i get some object, then I use some id from it (which will be number),
And try to get data for this object, it should be like this:
> http://localhost:3000/myObjects/otherObj/1234567891234567891

but ids truncated and it will be like this:

> http://localhost:3000/myObjects/otherObj/1234567891234567000

So there are a lot of logic for this..
And also:
> I am not sure is it bug or feature

i think that it is bug, because it is string and comparison should be done like for strings, not numbers, if i want numbers I will remove quotes, but i won't.

**Comment by yuridov** [comment]
It looks more as a bug rather than feature for me. I may have a generic text field as "fld":'foo', "fld":'bar', but a particular instance may be a number as "fld":'1'. Search for "?fld=foo" works fine, but "?fld=1" returns an empty result

**Comment by simeg** [comment]
This issue is fixed in PR #325.

**Comment by daveeel** [comment]
I'm using the latest version and still having the same issue, even with small number strings
My data is like:

`{ "type": "A", group: "2" } ...`

search by the following (e.g.):

`http://localhost:1234/data?group=2`

always gives empty result. Use string like `... group: "1-2"` has no issue
