### ISSUE TITLE
bug: start fails on node 10 with error message requiring node 4 or latest

### ISSUE THREAD

**Issue by NoNameProvided** [typicode/json-server#787]
When I try to run the `json-server` command, it exits with the following error message: 

```
json-server requires at least version 4 of Node, please upgrade
```

My node version is `v10.2.1` and I dont have any node version manager installed (`nvm`, etc.).

**Comment by typicode** [comment]
Hi @NoNameProvided,

There's a critical bug with `please-upgrade-node` and Node 10 (I've deprecated the versions containing this bug).

If you install `json-server` `v0.12.2`, it should fix the error.

**Comment by mateja176** [comment]
In addition to @typicode's answer, with `json-server@^0.12.0` ( which satisfies `json-server@0.12.2` ) the issue was still present. However running `npm i json-server@latest` updated `package.json` to 

```
  "json-server": "^0.15.0",

```

Solving the problem.

**Comment by soumenkundu** [comment]
> In addition to @typicode's answer, with `json-server@^0.12.0` ( which satisfies `json-server@0.12.2` ) the issue was still present. However running `npm i json-server@latest` updated `package.json` to
> 
> ```
>   "json-server": "^0.15.0",
> ```
> 
> Solving the problem.

Thanks. It solved my issue. My node version is 12.13.1

**Comment by VladimirLakodei** [comment]
The same problem. version 0.16.1

**Comment by tolgakurtulus** [comment]
You need to write terminal. npm i json-server@v0.12.2
